import "@/app/globals.css";
import { Header, Footer } from "@/components/ui";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className="h-full primary-background" lang="en">
      <body className="h-full">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
